version: '3.8'

services:
  go-app:
    build:
      context: ./path/to/go-application
    ports:
      - "8080:8080"

  nextjs-app:
    build:
      context: ./path/to/nextjs-application
    ports:
      - "3000:3000"

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - ./path/to/wordpress-site:/var/www/html/wp-content/themes/my-theme

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
